---
name: build-unsigned-genesis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://sui-releases.s3-accelerate.amazonaws.com/a63f425b9999c7fdfe483598720a9effc0acdc9e/sui
          chmod +x sui
      - run: |
          ./sui genesis-ceremony build-unsigned-checkpoint

      # Commit and upload unsigned genesis
      - run: |
          git config --global user.name "sui"
          git config --global user.email ""
          git add unsigned-genesis
          git commit -m "build unsigned genesis state"
          git push
