---
name: list-validators

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget https://sui-releases.s3-accelerate.amazonaws.com/a63f425b9999c7fdfe483598720a9effc0acdc9e/sui
          chmod +x sui
      - run: |
          ./sui genesis-ceremony list-validators
